SELECT t1.JOB_TITLE AS `Cargo`, ROUND(AVG(t2.SALARY), 2) AS `Média salarial`, 
CASE 
WHEN AVG(t2.SALARY) >= 2000 AND AVG(t2.SALARY) <= 5800 THEN 'Júnior'
WHEN AVG(t2.SALARY) > 5800 AND AVG(t2.SALARY) <= 7500 THEN 'Pleno'
WHEN AVG(t2.SALARY) > 7500 AND AVG(t2.SALARY) <= 10500 THEN 'Sênior'
WHEN AVG(t2.SALARY) > 10500 THEN 'CEO'
END AS `Senioridade`
FROM hr.jobs AS t1
INNER JOIN hr.employees as t2
ON 	t1.JOB_ID = t2.JOB_ID
GROUP BY JOB_TITLE
ORDER BY `Média salarial` ASC;
